# Generated by Django 2.1.7 on 2019-03-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='expertise',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skills',
            name='percentage',
            field=models.CharField(max_length=50),
        ),
    ]
