# Generated by Django 2.1.7 on 2019-03-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20190303_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
