# Generated by Django 2.1.7 on 2019-03-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_details_language_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='location',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
